services:
  - type: worker
    name: translate-bot
    env: node
    plan: free
    startCommand: node index.js
    envVars:
      - key: 8291112984:AAG6JkEg-bCJ8MKD-fV9f47sU1MsiAqB5Ak
        sync: false
